-- Crear tabla de usuarios admins
CREATE TABLE IF NOT EXISTS admins (
id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(255) NOT NULL,
email VARCHAR(255) NOT NULL UNIQUE,
password VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Crear tabla de personas
CREATE TABLE IF NOT EXISTS personas (
id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
nombre VARCHAR(255) NOT NULL,
about TEXT,
horario VARCHAR(255),
tarifa VARCHAR(50),
whatsapp VARCHAR(20),
telegram VARCHAR(50),
mapa TEXT,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

-- Crear tabla de tags
CREATE TABLE IF NOT EXISTS tags (
id INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
persona_id INT(10) UNSIGNED NOT NULL,
tipo VARCHAR(255) NOT NULL,
valor VARCHAR(255) NOT NULL,
created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
FOREIGN KEY (persona_id) REFERENCES personas(id) ON DELETE CASCADE
);
